/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import static java.lang.Math.random;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import static parkon.Main.st;
import static parkon.Utilities.*;

/**
 *
 * @author Xavier
 */
public class Floor1 extends javax.swing.JFrame {

    /**
     * Creates new form Floor1
     */
    
    public Floor1() {
        initComponents();
        this.setIconImage(new ImageIcon(this.getClass().getResource("/images/car-icon.png")).getImage());
        this.setLocationRelativeTo(null);
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Esc"); 
        getRootPane().getActionMap().put("Esc", new AbstractAction(){ 
            public void actionPerformed(ActionEvent e)
            {
                setVisible(false);
            }
        });
        updateFloor1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        place1 = new javax.swing.JButton();
        place2 = new javax.swing.JButton();
        place3 = new javax.swing.JButton();
        place4 = new javax.swing.JButton();
        place5 = new javax.swing.JButton();
        place6 = new javax.swing.JButton();
        place7 = new javax.swing.JButton();
        place8 = new javax.swing.JButton();
        place9 = new javax.swing.JButton();
        place10 = new javax.swing.JButton();
        place11 = new javax.swing.JButton();
        place12 = new javax.swing.JButton();
        place13 = new javax.swing.JButton();
        place14 = new javax.swing.JButton();
        place15 = new javax.swing.JButton();
        place16 = new javax.swing.JButton();
        place17 = new javax.swing.JButton();
        place18 = new javax.swing.JButton();
        place19 = new javax.swing.JButton();
        place20 = new javax.swing.JButton();
        place21 = new javax.swing.JButton();
        place22 = new javax.swing.JButton();
        place23 = new javax.swing.JButton();
        place24 = new javax.swing.JButton();
        place25 = new javax.swing.JButton();
        place26 = new javax.swing.JButton();
        place27 = new javax.swing.JButton();
        place28 = new javax.swing.JButton();
        place29 = new javax.swing.JButton();
        place30 = new javax.swing.JButton();
        place31 = new javax.swing.JButton();
        place32 = new javax.swing.JButton();
        place33 = new javax.swing.JButton();
        place34 = new javax.swing.JButton();
        place35 = new javax.swing.JButton();
        place36 = new javax.swing.JButton();
        place37 = new javax.swing.JButton();
        place38 = new javax.swing.JButton();
        place39 = new javax.swing.JButton();
        place40 = new javax.swing.JButton();
        place41 = new javax.swing.JButton();
        place42 = new javax.swing.JButton();
        place43 = new javax.swing.JButton();
        place44 = new javax.swing.JButton();
        place45 = new javax.swing.JButton();
        place46 = new javax.swing.JButton();
        place47 = new javax.swing.JButton();
        place48 = new javax.swing.JButton();
        place49 = new javax.swing.JButton();
        place50 = new javax.swing.JButton();
        place51 = new javax.swing.JButton();
        place52 = new javax.swing.JButton();
        place53 = new javax.swing.JButton();
        place54 = new javax.swing.JButton();
        place55 = new javax.swing.JButton();
        place56 = new javax.swing.JButton();
        place57 = new javax.swing.JButton();
        place58 = new javax.swing.JButton();
        place59 = new javax.swing.JButton();
        place60 = new javax.swing.JButton();
        place61 = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("ParkGood 2014 - Planta 1");
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        place1.setText("1");
        place1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place1ActionPerformed(evt);
            }
        });
        getContentPane().add(place1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 30, 20));

        place2.setText("2");
        place2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place2ActionPerformed(evt);
            }
        });
        getContentPane().add(place2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 30, 20));

        place3.setText("3");
        place3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place3ActionPerformed(evt);
            }
        });
        getContentPane().add(place3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 30, 20));

        place4.setText("4");
        place4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place4ActionPerformed(evt);
            }
        });
        getContentPane().add(place4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 30, 20));

        place5.setText("5");
        place5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place5ActionPerformed(evt);
            }
        });
        getContentPane().add(place5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, 30, 20));

        place6.setText("6");
        place6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place6ActionPerformed(evt);
            }
        });
        getContentPane().add(place6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 30, 20));

        place7.setText("7");
        place7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place7ActionPerformed(evt);
            }
        });
        getContentPane().add(place7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 30, 20));

        place8.setText("8");
        place8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place8ActionPerformed(evt);
            }
        });
        getContentPane().add(place8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 30, 20));

        place9.setText("9");
        place9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place9ActionPerformed(evt);
            }
        });
        getContentPane().add(place9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 30, 20));

        place10.setText("10");
        place10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place10ActionPerformed(evt);
            }
        });
        getContentPane().add(place10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 20, 20));

        place11.setText("11");
        place11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place11ActionPerformed(evt);
            }
        });
        getContentPane().add(place11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 30, 20));

        place12.setText("12");
        place12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place12ActionPerformed(evt);
            }
        });
        getContentPane().add(place12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 30, 20));

        place13.setText("13");
        place13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place13ActionPerformed(evt);
            }
        });
        getContentPane().add(place13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 20, 40));

        place14.setText("14");
        place14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place14ActionPerformed(evt);
            }
        });
        getContentPane().add(place14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 20, 30));

        place15.setText("15");
        place15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place15ActionPerformed(evt);
            }
        });
        getContentPane().add(place15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 20, 30));

        place16.setText("16");
        place16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place16ActionPerformed(evt);
            }
        });
        getContentPane().add(place16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 20, 40));

        place17.setText("17");
        place17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place17ActionPerformed(evt);
            }
        });
        getContentPane().add(place17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 20, 40));

        place18.setText("18");
        place18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place18ActionPerformed(evt);
            }
        });
        getContentPane().add(place18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 20, 40));

        place19.setText("19");
        place19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place19ActionPerformed(evt);
            }
        });
        getContentPane().add(place19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 20, 20));

        place20.setText("20");
        place20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place20ActionPerformed(evt);
            }
        });
        getContentPane().add(place20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 20, 20));

        place21.setText("21");
        place21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place21ActionPerformed(evt);
            }
        });
        getContentPane().add(place21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 30, -1));

        place22.setText("22");
        place22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place22ActionPerformed(evt);
            }
        });
        getContentPane().add(place22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 30, -1));

        place23.setText("23");
        place23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place23ActionPerformed(evt);
            }
        });
        getContentPane().add(place23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 30, -1));

        place24.setText("24");
        place24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place24ActionPerformed(evt);
            }
        });
        getContentPane().add(place24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 30, -1));

        place25.setText("25");
        place25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place25ActionPerformed(evt);
            }
        });
        getContentPane().add(place25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 40, -1));

        place26.setText("26");
        place26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place26ActionPerformed(evt);
            }
        });
        getContentPane().add(place26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 30, -1));

        place27.setText("27");
        place27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place27ActionPerformed(evt);
            }
        });
        getContentPane().add(place27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 30, -1));

        place28.setText("28");
        place28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place28ActionPerformed(evt);
            }
        });
        getContentPane().add(place28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 40, -1));

        place29.setText("29");
        place29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place29ActionPerformed(evt);
            }
        });
        getContentPane().add(place29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 40, -1));

        place30.setText("30");
        place30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place30ActionPerformed(evt);
            }
        });
        getContentPane().add(place30, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 30, -1));

        place31.setText("31");
        place31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place31ActionPerformed(evt);
            }
        });
        getContentPane().add(place31, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 30, -1));

        place32.setText("32");
        place32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place32ActionPerformed(evt);
            }
        });
        getContentPane().add(place32, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 40, -1));

        place33.setText("33");
        place33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place33ActionPerformed(evt);
            }
        });
        getContentPane().add(place33, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 20, -1));

        place34.setText("34");
        place34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place34ActionPerformed(evt);
            }
        });
        getContentPane().add(place34, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 20, 20));

        place35.setText("35");
        place35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place35ActionPerformed(evt);
            }
        });
        getContentPane().add(place35, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 20, 30));

        place36.setText("36");
        place36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place36ActionPerformed(evt);
            }
        });
        getContentPane().add(place36, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 20, 30));

        place37.setText("37");
        place37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place37ActionPerformed(evt);
            }
        });
        getContentPane().add(place37, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 20, 30));

        place38.setText("38");
        place38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place38ActionPerformed(evt);
            }
        });
        getContentPane().add(place38, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 40, 20));

        place39.setText("39");
        place39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place39ActionPerformed(evt);
            }
        });
        getContentPane().add(place39, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 30, 20));

        place40.setText("40");
        place40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place40ActionPerformed(evt);
            }
        });
        getContentPane().add(place40, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 30, 20));

        place41.setText("41");
        place41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place41ActionPerformed(evt);
            }
        });
        getContentPane().add(place41, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 30, 20));

        place42.setText("42");
        place42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place42ActionPerformed(evt);
            }
        });
        getContentPane().add(place42, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 30, 20));

        place43.setText("43");
        place43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place43ActionPerformed(evt);
            }
        });
        getContentPane().add(place43, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 30, 20));

        place44.setText("44");
        place44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place44ActionPerformed(evt);
            }
        });
        getContentPane().add(place44, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 40, 20));

        place45.setText("45");
        place45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place45ActionPerformed(evt);
            }
        });
        getContentPane().add(place45, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 30, 20));

        place46.setText("46");
        place46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place46ActionPerformed(evt);
            }
        });
        getContentPane().add(place46, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 40, 20));

        place47.setText("47");
        place47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place47ActionPerformed(evt);
            }
        });
        getContentPane().add(place47, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 30, 20));

        place48.setText("48");
        place48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place48ActionPerformed(evt);
            }
        });
        getContentPane().add(place48, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 20, 20));

        place49.setText("49");
        place49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place49ActionPerformed(evt);
            }
        });
        getContentPane().add(place49, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 30, 20));

        place50.setText("50");
        place50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place50ActionPerformed(evt);
            }
        });
        getContentPane().add(place50, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 20, 20));

        place51.setText("51");
        place51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place51ActionPerformed(evt);
            }
        });
        getContentPane().add(place51, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 40, 20));

        place52.setText("52");
        place52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place52ActionPerformed(evt);
            }
        });
        getContentPane().add(place52, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 30, 20));

        place53.setText("53");
        place53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place53ActionPerformed(evt);
            }
        });
        getContentPane().add(place53, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 40, 20));

        place54.setText("54");
        place54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place54ActionPerformed(evt);
            }
        });
        getContentPane().add(place54, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 20, 20));

        place55.setText("55");
        place55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place55ActionPerformed(evt);
            }
        });
        getContentPane().add(place55, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 20, 20));

        place56.setText("56");
        place56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place56ActionPerformed(evt);
            }
        });
        getContentPane().add(place56, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 20, 20));

        place57.setText("57");
        place57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place57ActionPerformed(evt);
            }
        });
        getContentPane().add(place57, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 20, 20));

        place58.setText("58");
        place58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place58ActionPerformed(evt);
            }
        });
        getContentPane().add(place58, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 30, 20));

        place59.setText("59");
        place59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place59ActionPerformed(evt);
            }
        });
        getContentPane().add(place59, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 30, 20));

        place60.setText("60");
        place60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place60ActionPerformed(evt);
            }
        });
        getContentPane().add(place60, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 20, 20));

        place61.setText("61");
        place61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place61ActionPerformed(evt);
            }
        });
        getContentPane().add(place61, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 20, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/floor1.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setText("PLANTA 1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void place19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place19ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place19ActionPerformed

    private void place20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place20ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place20ActionPerformed

    private void place21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place21ActionPerformed
       readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place21ActionPerformed

    private void place22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place22ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place22ActionPerformed

    private void place23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place23ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place23ActionPerformed

    private void place24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place24ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place24ActionPerformed

    private void place25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place25ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place25ActionPerformed

    private void place26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place26ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place26ActionPerformed

    private void place27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place27ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place27ActionPerformed

    private void place28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place28ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place28ActionPerformed

    private void place29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place29ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place29ActionPerformed

    private void place30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place30ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place30ActionPerformed

    private void place31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place31ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place31ActionPerformed

    private void place32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place32ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place32ActionPerformed

    private void place33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place33ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place33ActionPerformed

    private void place34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place34ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place34ActionPerformed

    private void place35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place35ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place35ActionPerformed

    private void place36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place36ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place36ActionPerformed

    private void place37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place37ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place37ActionPerformed

    private void place38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place38ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place38ActionPerformed

    private void place39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place39ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place39ActionPerformed

    private void place40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place40ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place40ActionPerformed

    private void place41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place41ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place41ActionPerformed

    private void place42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place42ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place42ActionPerformed

    private void place43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place43ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place43ActionPerformed

    private void place44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place44ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place44ActionPerformed

    private void place45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place45ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place45ActionPerformed

    private void place46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place46ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place46ActionPerformed

    private void place47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place47ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place47ActionPerformed

    private void place48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place48ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place48ActionPerformed

    private void place49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place49ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place49ActionPerformed

    private void place50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place50ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place50ActionPerformed

    private void place51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place51ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place51ActionPerformed

    private void place52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place52ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place52ActionPerformed

    private void place53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place53ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place53ActionPerformed

    private void place54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place54ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place54ActionPerformed

    private void place56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place56ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place56ActionPerformed

    private void place57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place57ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place57ActionPerformed

    private void place55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place55ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place55ActionPerformed

    private void place58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place58ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place58ActionPerformed

    private void place59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place59ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place59ActionPerformed

    private void place60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place60ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place60ActionPerformed

    private void place1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place1ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place1ActionPerformed

    private void place2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place2ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place2ActionPerformed

    private void place3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place3ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place3ActionPerformed

    private void place4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place4ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place4ActionPerformed

    private void place5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place5ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place5ActionPerformed

    private void place6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place6ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place6ActionPerformed

    private void place7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place7ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place7ActionPerformed

    private void place8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place8ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place8ActionPerformed

    private void place9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place9ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place9ActionPerformed

    private void place10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place10ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place10ActionPerformed

    private void place11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place11ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place11ActionPerformed

    private void place12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place12ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place12ActionPerformed

    private void place13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place13ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place13ActionPerformed

    private void place14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place14ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place14ActionPerformed

    private void place15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place15ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place15ActionPerformed

    private void place16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place16ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place16ActionPerformed

    private void place17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place17ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place17ActionPerformed

    private void place18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place18ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place18ActionPerformed

    private void place61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place61ActionPerformed
        readInfo(evt.getActionCommand(), 100);
    }//GEN-LAST:event_place61ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Extra E = new Extra(1);
        E.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JButton place1;
    public static javax.swing.JButton place10;
    public static javax.swing.JButton place11;
    public static javax.swing.JButton place12;
    public static javax.swing.JButton place13;
    public static javax.swing.JButton place14;
    public static javax.swing.JButton place15;
    public static javax.swing.JButton place16;
    public static javax.swing.JButton place17;
    public static javax.swing.JButton place18;
    public static javax.swing.JButton place19;
    public static javax.swing.JButton place2;
    public static javax.swing.JButton place20;
    public static javax.swing.JButton place21;
    public static javax.swing.JButton place22;
    public static javax.swing.JButton place23;
    public static javax.swing.JButton place24;
    public static javax.swing.JButton place25;
    public static javax.swing.JButton place26;
    public static javax.swing.JButton place27;
    public static javax.swing.JButton place28;
    public static javax.swing.JButton place29;
    public static javax.swing.JButton place3;
    public static javax.swing.JButton place30;
    public static javax.swing.JButton place31;
    public static javax.swing.JButton place32;
    public static javax.swing.JButton place33;
    public static javax.swing.JButton place34;
    public static javax.swing.JButton place35;
    public static javax.swing.JButton place36;
    public static javax.swing.JButton place37;
    public static javax.swing.JButton place38;
    public static javax.swing.JButton place39;
    public static javax.swing.JButton place4;
    public static javax.swing.JButton place40;
    public static javax.swing.JButton place41;
    public static javax.swing.JButton place42;
    public static javax.swing.JButton place43;
    public static javax.swing.JButton place44;
    public static javax.swing.JButton place45;
    public static javax.swing.JButton place46;
    public static javax.swing.JButton place47;
    public static javax.swing.JButton place48;
    public static javax.swing.JButton place49;
    public static javax.swing.JButton place5;
    public static javax.swing.JButton place50;
    public static javax.swing.JButton place51;
    public static javax.swing.JButton place52;
    public static javax.swing.JButton place53;
    public static javax.swing.JButton place54;
    public static javax.swing.JButton place55;
    public static javax.swing.JButton place56;
    public static javax.swing.JButton place57;
    public static javax.swing.JButton place58;
    public static javax.swing.JButton place59;
    public static javax.swing.JButton place6;
    public static javax.swing.JButton place60;
    public static javax.swing.JButton place61;
    public static javax.swing.JButton place7;
    public static javax.swing.JButton place8;
    public static javax.swing.JButton place9;
    // End of variables declaration//GEN-END:variables
}
